name: Retrieve Latest Posts

on:
  push:
    branches:
      - main

jobs:
  extract_and_store:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Retrieve Latest Posts
        run: node getLatestPosts.js

      - name: Commit Changes
        run: |
          git config --global user.name "hamdivazim"
          git config --global user.email "coding.wizard4@gmail.com"
          git add .
          git commit -m "Push recent posts (on behalf of hamdivazim)"
        
      - name: Push Changes
        run: |
          git push origin main

